version: '3'

services:
  node:
    container_name: youtube_timestamp
    build: .
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd youtube-timestamp && yarn start'
    ports:
      - '3000:3000'